# Generated by Django 5.2.1 on 2025-05-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_name', models.CharField(max_length=255)),
                ('number_of_bids', models.IntegerField()),
                ('total_bids', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('bidding_start_time', models.DateTimeField()),
                ('bidding_end_time', models.DateTimeField()),
                ('total_time_seconds', models.IntegerField()),
                ('total_client_spending', models.DecimalField(decimal_places=2, max_digits=12)),
                ('client_average_hour_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bidder_job_country', models.CharField(max_length=255)),
                ('pipeline', models.CharField(max_length=255)),
            ],
        ),
    ]
